language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
services: postgresql
before_script:
  - psql -c 'create database pgbuilder_test' -U postgres -h 127.0.0.1
  - cp tests/config.php.travis tests/config.php
install: composer install --no-dev
script: phpunit --configuration tests/phpunit.xml
